version: "3.3"
services: 
  http-callback:
    network_mode: "host"
    container_name: http-callback
    build: 
      context: .
      dockerfile: Dockerfile
    image: http-callback:latest
    env_file: 
      .env
    volumes:
      - ./static/:/app/http-callback/static
    depends_on:
      - redis-callback
    networks:
      - http-callback-network
  redis-callback:
    container_name: redis-callback
    image: redis:6-alpine
    restart: always
    command: redis-server
    hostname: redis-callback
    ports:
      - 6381:6379
    networks:
      - http-callback-network